from typing import TypedDict, List, Dict, Any, Annotated
import operator

class SynapseState(TypedDict):
    """
    The central state object for the SynapseAI LangGraph workflow.
    Every node reads from this and updates specific fields.
    """
    
    user_prompt: str 
    
    # --- Phase 1: Planning & Evaluation ---
    current_dag: Dict[str, Any]  # The JSON plan generated by Groq
    judge_score: float           # The Answer Relevancy score (0.0 to 1.0)
    feedback: str                # The critique provided by the Gemini Judge
    loop_count: int              # Tracks generation attempts to prevent infinite loops
    
    # --- Phase 2 & 3: Execution & Reflexion ---
    current_step_id: str         # Tracks which step in the DAG the executor is currently on
    
    # The Reflexion Scratchpad uses Annotated + operator.add.
    # This tells LangGraph to APPEND new logs to this list rather than OVERWRITING it.
    reflexion_scratchpad: Annotated[List[str], operator.add] 
     # Made Optional so the graph can reach END without having set these
    # --- The Output ---
    final_output: str            # The final result delivered back to the user
    useful_output: True
    execution_warnings: Annotated[List[dict], operator.add]